core:
  build: ./core/
  ports: 
    - "8003:8003"
  environment:
    - FLASK_DEBUG="True"
    - FLASK_RETHINKDB_HOST="rethinkdb"
  volumes:
    - ./core/:/app
  command: python manage.py runserver --host 0.0.0.0 --port 8003

marketplace:
    build: ./marketplace/
    ports:
        - "8001:8001"
    volumes:
        - ./marketplace/:/app
    command: python -m SimpleHTTPServer 8001


rethinkdb:
  image: rethinkdb
  ports:
    - "8080:8080"